namespace TitanBot
{
    public enum PTAction
    {
        Attack,
        Jump,
        AttackII,
        Suicide,
        grabbackl,
        grabbackr,
        grabfrontl,
        grabfrontr,
        grabnapel,
        grabnaper,
        choptl,
        chopr,
        chopl,
        choptr,
        bite,
        bitel,
        biter,
        cover,
        sit,
        combo_2,
        combo_3,
        front_ground,
        kick,
        slap_back,
        slap_face,
        stomp,
        crawler_jump_0,
        nothing
    }
}
